# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_datafile', models.FileField(upload_to='raw_data/%Y/%m/%d')),
                ('processed_datafile', models.FileField(upload_to='processed_data/%Y/%m/%d')),
                ('start_time', models.FloatField(default='-inf')),
                ('finish_time', models.FloatField(default='inf')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('start_time_unix', models.FloatField(blank=True, null=True)),
                ('finish_time_unix', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('left_hand_file', models.ManyToManyField(blank=True, related_name='left_hand', to='arms.DataFile')),
                ('right_hand_file', models.ManyToManyField(blank=True, related_name='right_hand', to='arms.DataFile')),
            ],
        ),
    ]
