# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='view_div',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='view_script',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
