# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0002_auto_20170408_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='activity_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
